title: Harrix
author: GitHub User
email: TODO@mail.ru
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
# twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "harrix.dev"
github_username:  harrix

show_excerpts: true # set to true to show excerpts on the homepage

markdown: kramdown
#kramdown:
#  math_engine: nil

pagination:
  enabled: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

scholar:
  style: apa
  locale: ru
  repository: publications
  bibliography_template: bibliography

defaults:
  -
    scope:
      path: "_posts/blog"
      type: posts
    values:
      layout: post
      categories: [blog]
  -
    scope:
      path: "_posts/games"
      type: posts
    values:
      layout: post
      categories: [games]

destination: ../dist